name: CI Pipeline
on: [push, pull_request]  # Запуск при пуше и PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Загружаем код
      - uses: actions/checkout@v2
      
      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      
      
      - name: Build and test server
          run: |
            cd server
            npm run build # Теперь это включает и тесты
      
      - name: Build and test client
        run: |
          cd client
          npm install
          npm run build
          npm test
