name: CI Pipeline
on: [push, pull_request]  # Запуск при пуше и PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Загружаем код
      - uses: actions/checkout@v2
      
      # Шаг 2: Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      
      # Этап BUILD для сервера
      - name: Build server
        run: |
          cd server
          npm install
          npm run build  # Если есть скрипт build в package.json
      
      # Этап TEST для сервера
      - name: Test server
        run: |
          cd server
          npm test
      
      # Этап BUILD для клиента
      - name: Build client
        run: |
          cd client
          npm install
          npm run build
      
      # Этап TEST для клиента
      - name: Test client
        run: |
          cd client
          npm test