name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ===== СБОРКА SERVER =====
      - name: Install server dependencies
        run: |
          cd server
          npm install

      # ===== СБОРКА CLIENT =====
      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build || echo "No build script in client"

  test:
    runs-on: ubuntu-latest
    needs: build  # Запускается после билда

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ===== ТЕСТЫ SERVER =====
      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run server tests
        run: |
          cd server
          npm test -- --passWithNoTests

      # ===== ТЕСТЫ CLIENT =====
      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Run client tests
        run: |
          cd client
          npm test -- --passWithNoTests || echo "No tests in client"